/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 投满满SAAS - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.get_api_device_clear': ['GET', '/api/device/clear'],
  'general.post_collect_uploadlog': ['POST', '/collect/uploadLog'],
  'general.get_api_appuser_login': ['GET', '/api/appUser/login'],
  'general.post_api_appuser_login': ['POST', '/api/appUser/login'],
  'general.get_api_qrcode_scan': ['GET', '/api/qrcode/scan'],
  'general.post_https_api_weixin_qq_com_cgi_bin_stable_token': [
    'POST',
    'https://api.weixin.qq.com/cgi-bin/stable_token'
  ],
  'general.get_app_api_client_auth': ['GET', '/app-api/client/auth'],
  'general.get_collect_qrcode': ['GET', '/collect/qrCode'],
  'general.post_collect_deliver': ['POST', '/collect/deliver'],
  'general.post_app_api_collect_clear': ['POST', '/app-api/collect/clear'],
  'general.get_collect_bind': ['GET', '/collect/bind'],
  'general.get_collect_config': ['GET', '/collect/config'],
  'general.post_collect_listappuser': ['POST', '/collect/listAppUser'],
  'general.get_collect_phonelogin': ['GET', '/collect/phoneLogin'],
  'general.post_collect_report': ['POST', '/collect/report'],
  'general.get_collect_smokealarm': ['GET', '/collect/smokeAlarm'],
  'general.get_collect_full': ['GET', '/collect/full'],
  'general.post_app_api_collect_upload': ['POST', '/app-api/collect/upload'],
  'general.post_collect_loginfo': ['POST', '/collect/logInfo'],
  'general.get_collect_unbind': ['GET', '/collect/unbind'],
  'general.get_app_api_client_refresh_token': ['GET', '/app-api/client/refresh-token'],
  'general.get_app_api_client_login': ['GET', '/app-api/client/login'],
  'general.get_app_api_client_getphone': ['GET', '/app-api/client/getPhone'],
  'general.get_collect_createqrcode': ['GET', '/collect/createQrCode'],
  'general.get_api_v2_version': ['GET', '/api/v2/version'],
  'general.get_api_appuser_accreditlogin': ['GET', '/api/appUser/accreditLogin'],
  'general.get_http_192_168_1_125_cgi_bin_snapshot_cgi_username_admin_password_123456': [
    'GET',
    'http://192.168.1.125/cgi-bin/snapshot.cgi&username=admin&password=123456'
  ]
};
