/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 宠物API - version 1.0
 *
 * 猫和狗的CRUD API演示
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'App.AppController_getHello': ['GET', '/'],
  'Cats.CatsController_create': ['POST', '/cats'],
  'Cats.CatsController_findAll': ['GET', '/cats'],
  'Cats.CatsController_findOne': ['GET', '/cats/{id}'],
  'Cats.CatsController_update': ['PATCH', '/cats/{id}'],
  'Cats.CatsController_remove': ['DELETE', '/cats/{id}']
};
