/* tslint:disable */
/* eslint-disable */
/**
 * 投满满SAAS - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

declare global {
  interface Apis {
    general: {
      /**
       * ---
       *
       * [GET] 清运
       *
       * **path:** /api/device/clear
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // [required]
       *   deviceId: string
       *   // [required]
       *   deviceNo: string
       *   // [required]
       *   bucketId: string
       *   // [required]
       *   bagNo: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_api_device_clear<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * [required]
             */
            deviceId: string;
            /**
             * [required]
             */
            deviceNo: string;
            /**
             * [required]
             */
            bucketId: string;
            /**
             * [required]
             */
            bagNo: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.get_api_device_clear', Config>;
      /**
       * ---
       *
       * [POST] 上传日志文件
       *
       * **path:** /collect/uploadLog
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   deviceNo?: string
       *   file?: Blob
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      post_collect_uploadlog<
        Config extends Alova2MethodConfig<object> & {
          data: {
            deviceNo?: string;
            file?: Blob;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.post_collect_uploadlog', Config>;
      /**
       * ---
       *
       * [GET] 获取token
       *
       * **path:** /api/appUser/login
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // [required]
       *   phone: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_api_appuser_login<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * [required]
             */
            phone: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.get_api_appuser_login', Config>;
      /**
       * ---
       *
       * [POST] 清运员登录
       *
       * **path:** /api/appUser/login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      post_api_appuser_login<
        Config extends Alova2MethodConfig<object> & {
          data: object;
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.post_api_appuser_login', Config>;
      /**
       * ---
       *
       * [GET] 扫码登录
       *
       * **path:** /api/qrcode/scan
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 设备编号
       *   // [required]
       *   uuid: string
       *   // 二维码id
       *   // [required]
       *   qrcodeId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_api_qrcode_scan<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * 设备编号
             * [required]
             */
            uuid: string;
            /**
             * 二维码id
             * [required]
             */
            qrcodeId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.get_api_qrcode_scan', Config>;
      /**
       * ---
       *
       * [POST] 获取token
       *
       * **path:** https://api.weixin.qq.com/cgi-bin/stable_token
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      post_https_api_weixin_qq_com_cgi_bin_stable_token<
        Config extends Alova2MethodConfig<object> & {
          data: object;
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.post_https_api_weixin_qq_com_cgi_bin_stable_token', Config>;
      /**
       * ---
       *
       * [GET] 微信授权
       *
       * **path:** /app-api/client/auth
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 微信code
       *   // [required]
       *   code: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_app_api_client_auth<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * 微信code
             * [required]
             */
            code: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.get_app_api_client_auth', Config>;
      /**
       * ---
       *
       * [GET] 获取二维码
       *
       * **path:** /collect/qrCode
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // [required]
       *   deviceNo: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_collect_qrcode<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * [required]
             */
            deviceNo: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.get_collect_qrcode', Config>;
      /**
       * ---
       *
       * [POST] 投递
       *
       * **path:** /collect/deliver
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      post_collect_deliver<
        Config extends Alova2MethodConfig<object> & {
          data: object;
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.post_collect_deliver', Config>;
      /**
       * ---
       *
       * [POST] 清运
       *
       * **path:** /app-api/collect/clear
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      post_app_api_collect_clear<
        Config extends Alova2MethodConfig<object> & {
          data: object;
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.post_app_api_collect_clear', Config>;
      /**
       * ---
       *
       * [GET] 绑定
       *
       * **path:** /collect/bind
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 设备编号必填
       *   // [required]
       *   deviceNo: string
       *   // padId 平板唯一标识 必填
       *   // [required]
       *   padId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_collect_bind<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * 设备编号必填
             * [required]
             */
            deviceNo: string;
            /**
             * padId 平板唯一标识 必填
             * [required]
             */
            padId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.get_collect_bind', Config>;
      /**
       * ---
       *
       * [GET] 获取配置
       *
       * **path:** /collect/config
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 设备编号必填
       *   // [required]
       *   deviceNo: string
       *   // 当前设备的版本号 必填
       *   // [required]
       *   version: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_collect_config<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * 设备编号必填
             * [required]
             */
            deviceNo: string;
            /**
             * 当前设备的版本号 必填
             * [required]
             */
            version: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.get_collect_config', Config>;
      /**
       * ---
       *
       * [POST] 用户加密列表
       *
       * **path:** /collect/listAppUser
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      post_collect_listappuser<Config extends Alova2MethodConfig<object>>(
        config?: Config
      ): Alova2Method<object, 'general.post_collect_listappuser', Config>;
      /**
       * ---
       *
       * [GET] 手机号登录
       *
       * **path:** /collect/phoneLogin
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 手机号
       *   // [required]
       *   phone: string
       *   // 设备编号必填
       *   // [required]
       *   deviceNo: string
       *   // [required]
       *   deviceId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_collect_phonelogin<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * 手机号
             * [required]
             */
            phone: string;
            /**
             * 设备编号必填
             * [required]
             */
            deviceNo: string;
            /**
             * [required]
             */
            deviceId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.get_collect_phonelogin', Config>;
      /**
       * ---
       *
       * [POST] 截图上报图片
       *
       * **path:** /collect/report
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // [required]
       *   deviceNo: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   file?: Blob
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      post_collect_report<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * [required]
             */
            deviceNo: string;
          };
          data: {
            file?: Blob;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.post_collect_report', Config>;
      /**
       * ---
       *
       * [GET] 烟雾
       *
       * **path:** /collect/smokeAlarm
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 设备编号
       *   // [required]
       *   deviceNo: string
       *   // 状态
       *   // [required]
       *   status: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_collect_smokealarm<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * 设备编号
             * [required]
             */
            deviceNo: string;
            /**
             * 状态
             * [required]
             */
            status: string;
          };
          data: object;
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.get_collect_smokealarm', Config>;
      /**
       * ---
       *
       * [GET] 满溢
       *
       * **path:** /collect/full
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 设备编号
       *   // [required]
       *   deviceNo: string
       *   // 状态 1满溢 0未满溢
       *   // [required]
       *   full: string
       *   // [required]
       *   bucketNo: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_collect_full<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * 设备编号
             * [required]
             */
            deviceNo: string;
            /**
             * 状态 1满溢 0未满溢
             * [required]
             */
            full: string;
            /**
             * [required]
             */
            bucketNo: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.get_collect_full', Config>;
      /**
       * ---
       *
       * [POST] 上传图片
       *
       * **path:** /app-api/collect/upload
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // [required]
       *   name: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   file?: Blob
       *   // 图片类型 1投递 3清运
       *   imageType?: string
       *   // 业务主键 需要在设备本地数据库唯一
       *   deliverPrimary?: string
       *   // 图片索引 1安防监控 2开门  3关门
       *   imageIndex?: string
       *   // 桶id
       *   bucketId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      post_app_api_collect_upload<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * [required]
             */
            name: string;
          };
          data: {
            file?: Blob;
            /**
             * 图片类型 1投递 3清运
             */
            imageType?: string;
            /**
             * 业务主键 需要在设备本地数据库唯一
             */
            deliverPrimary?: string;
            /**
             * 图片索引 1安防监控 2开门  3关门
             */
            imageIndex?: string;
            /**
             * 桶id
             */
            bucketId?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.post_app_api_collect_upload', Config>;
      /**
       * ---
       *
       * [POST] 上传日志信息
       *
       * **path:** /collect/logInfo
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // [required]
       *   deviceNo: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      post_collect_loginfo<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * [required]
             */
            deviceNo: string;
          };
          data: object;
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.post_collect_loginfo', Config>;
      /**
       * ---
       *
       * [GET] 解绑
       *
       * **path:** /collect/unbind
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 设备编号必填
       *   // [required]
       *   deviceNo: string
       *   // padId 平板唯一标识 必填
       *   // [required]
       *   padId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_collect_unbind<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * 设备编号必填
             * [required]
             */
            deviceNo: string;
            /**
             * padId 平板唯一标识 必填
             * [required]
             */
            padId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.get_collect_unbind', Config>;
      /**
       * ---
       *
       * [GET] 刷新token
       *
       * **path:** /app-api/client/refresh-token
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // refreshToken
       *   // [required]
       *   refreshToken: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_app_api_client_refresh_token<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * refreshToken
             * [required]
             */
            refreshToken: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.get_app_api_client_refresh_token', Config>;
      /**
       * ---
       *
       * [GET] 登录
       *
       * **path:** /app-api/client/login
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 手机号 必填
       *   // [required]
       *   phone: null
       *   // 设备编号 非必填 如果是通过微信扫描二维码跳转登录的需要携带参数 非必填
       *   // [required]
       *   deviceNo: string
       *   // 授权id 调用微信授权接口是返回的authId 必填
       *   // [required]
       *   authId: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_app_api_client_login<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * 手机号 必填
             * [required]
             */
            phone: null;
            /**
             * 设备编号 非必填 如果是通过微信扫描二维码跳转登录的需要携带参数 非必填
             * [required]
             */
            deviceNo: string;
            /**
             * 授权id 调用微信授权接口是返回的authId 必填
             * [required]
             */
            authId: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.get_app_api_client_login', Config>;
      /**
       * ---
       *
       * [GET] 获取手机号
       *
       * **path:** /app-api/client/getPhone
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 微信code
       *   // [required]
       *   code: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_app_api_client_getphone<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * 微信code
             * [required]
             */
            code: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.get_app_api_client_getphone', Config>;
      /**
       * ---
       *
       * [GET] 创建二维码
       *
       * **path:** /collect/createQrCode
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 设备编号必填
       *   // [required]
       *   deviceNo: string
       *   // 二维码id  全局唯一
       *   // [required]
       *   qrcodeId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_collect_createqrcode<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * 设备编号必填
             * [required]
             */
            deviceNo: string;
            /**
             * 二维码id  全局唯一
             * [required]
             */
            qrcodeId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.get_collect_createqrcode', Config>;
      /**
       * ---
       *
       * [GET] 获取最新版本
       *
       * **path:** /api/v2/version
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_api_v2_version<Config extends Alova2MethodConfig<object>>(
        config?: Config
      ): Alova2Method<object, 'general.get_api_v2_version', Config>;
      /**
       * ---
       *
       * [GET] 登录
       *
       * **path:** /api/appUser/accreditLogin
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // [required]
       *   phone: string
       *   // [required]
       *   deviceNo: string
       *   // [required]
       *   authId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_api_appuser_accreditlogin<
        Config extends Alova2MethodConfig<object> & {
          params: {
            /**
             * [required]
             */
            phone: string;
            /**
             * [required]
             */
            deviceNo: string;
            /**
             * [required]
             */
            authId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.get_api_appuser_accreditlogin', Config>;
      /**
       * ---
       *
       * [GET] 安防监控拍照
       *
       * **path:** http://192.168.1.125/cgi-bin/snapshot.cgi&username=admin&password=123456
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_http_192_168_1_125_cgi_bin_snapshot_cgi_username_admin_password_123456<
        Config extends Alova2MethodConfig<object>
      >(
        config?: Config
      ): Alova2Method<
        object,
        'general.get_http_192_168_1_125_cgi_bin_snapshot_cgi_username_admin_password_123456',
        Config
      >;
    };
  }

  var Apis: Apis;
}
